### ISSUE TITLE
Reload/reconnect button?

### ISSUE THREAD

**Issue by sndrtj** [varapp/varapp-backend-py#2]
Hi there once more,

I'm getting some intermittent connection errors, which result in `Internal server error`, which do not get resolved until I reload the application. 
My databases reside on a mounted network drive (mounted via `sshfs`) and my guess is that this connection might occasionally jitter. For most applications this is not a huge issue, but it seems that once varapp has a connection failure, it will keep on failing until I reload the entire application. 

The exact error I get in the logs:

```
ERROR [django.request] Internal Server Error: /varapp/the_database/stats
Traceback (most recent call last):
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/utils.py", line 177, in ensure_defaults
    conn = self.databases[alias]
KeyError: 'the_database'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/varapp_env/lib/python3.4/site-packages/django_jsonview-0.5.0-py3.4.egg/jsonview/decorators.py", line 83, in _wrapped
    ret = f(request, *a, **kw)
  File "./varapp/views/views.py", line 89, in stats
    stat = stats_service(db).get_global_stats()
  File "./varapp/stats/stats_service.py", line 217, in stats_service
    return GlobalStatsService(db)
  File "./varapp/stats/stats_service.py", line 44, in __init__
    self._N = self._initqs.count()
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/models/query.py", line 371, in count
    return self.query.get_count(using=self.db)
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/models/sql/query.py", line 483, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/models/sql/query.py", line 463, in get_aggregation
    compiler = outer_query.get_compiler(using)
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/models/sql/query.py", line 254, in get_compiler
    connection = connections[using]
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/utils.py", line 209, in __getitem__
    self.ensure_defaults(alias)
  File "/home/user/varapp_env/lib/python3.4/site-packages/Django-1.9.6-py3.4.egg/django/db/utils.py", line 179, in ensure_defaults
    raise ConnectionDoesNotExist("The connection %s doesn't exist" % alias)
django.db.utils.ConnectionDoesNotExist: The connection the_database doesn't exist
```

I think it'd be nice of there was some way to attempt to restore the connection once it's lost.

**Comment by jdelafon** [comment]
Hi, thanks for reporting.

I have been working on making the "connections" more stable in the past few days (allowing to add/remove/edit dbs without restarting) and it was released the day before yesterday I believe. 
Although not perfect yet, this new version should solve the problem if you don't mind reinstalling the backend (I simplified the process and the docs a bit, and the current dev has no more compiling step). 
There will be a second release at the end of next week to fix cases where there can be double inserts after an edit when using multiple apache processes.

In the older version, connections are created when wsgi is started, so restarting mod_wsgi should solve it. Anyway before the update there was no way to add or remove a db without restarting the app. I was using a "restart_wsgi" shell script, because you can't do that from the app itself.

If the issue is not solved by the new version, i could add a button as a temporary fix. But this refresh could happen on every page reload, which I would prefer. Now it should.
I will do more tests when I come back on Tuesday.

Julien

**Comment by sndrtj** [comment]
Hi,

You're entirely correct that I tried this on the older version. If it is fixed in the newest version, that'd be great. Will try it on the newest tomorrow or somewhere during the weekend :-). 

Cheers,
Sander.

**Comment by jdelafon** [comment]
I released the new version yesterday, with many tests about connections (although processes concurrency is a hard thing to test), a simplified installation, and updated docs. I hope this issue is solved.
